### ISSUE TITLE
Error when setting up project with With Docker Compose

### ISSUE THREAD

**Issue by alexio545** [jomariya23156/sales-forecast-mlops-at-scale#1] opened 2024-04-26 19:42 UTC
After running the following command `docker-compose -f docker-compose.yml -f docker-compose-airflow.yml up -d` im getting the error below 
```
` => [nginx 2/3] COPY default.conf.template /etc/nginx/templates/                                                                      0.5s
 => ERROR [nginx 3/3] RUN ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log                 1.5s
------
 > [nginx 3/3] RUN ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log:
1.430 exec /bin/sh: exec format error
------
failed to solve: process "/bin/sh -c ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log" did not complete successfully: exit code: 1```



**and `docker-compose build` is also giving the following error**

` => ERROR [ray 2/4] RUN mkdir -p /storage/mlruns/ &&     chown -R ray /storage/mlruns/ &&     chmod -R go+rX /storage/mlruns/         1.4s
 => CACHED [mlflow 1/5] FROM docker.io/library/python:3.9.17-slim@sha256:42a5da33675ec5a692e8cdbb09ffa4e39588c10dd9a96235e543c498484  0.0s
 => [web-ui internal] load build context                                                                                              0.9s
 => => transferring context: 14.81kB                                                                                                  0.0s
 => [data-producer internal] load build context                                                                                       1.6s
 => => transferring context: 34.01MB                                                                                                  0.4s
 => ERROR [data-producer 2/7] RUN mkdir -p /service/datasets                                                                          1.7s
 => [mlflow internal] load build context                                                                                              1.2s
 => => transferring context: 79B                                                                                                      0.0s
 => [forecast-service internal] load build context                                                                                    0.6s
 => => transferring context: 6.80kB                                                                                                   0.0s
 => CACHED [forecast-service 2/5] COPY requirements.txt /service/requirements.txt                                                     0.1s
 => CACHED [web-ui 2/5] COPY requirements.txt /service/requirements.txt                                                               0.0s
 => CANCELED [web-ui 3/5] RUN pip install -r /service/requirements.txt                                                                1.8s
 => CANCELED [forecast-service 3/5] RUN pip install -r /service/requirements.txt                                                      2.1s
 => CACHED [mlflow 2/3] COPY requirements.txt .                                                                                       0.0s
 => CANCELED [mlflow 3/3] RUN pip install -r requirements.txt                                                                         2.3s
------
 > [ray 2/4] RUN mkdir -p /storage/mlruns/ &&     chown -R ray /storage/mlruns/ &&     chmod -R go+rX /storage/mlruns/:
0.884 exec /bin/bash: exec format error
------
------
 > [data-producer 2/7] RUN mkdir -p /service/datasets:
1.488 exec /bin/sh: exec format error
------
failed to solve: process "/bin/bash -c mkdir -p $MLFLOW_ARTIFACT_ROOT &&     chown -R ray $MLFLOW_ARTIFACT_ROOT &&     chmod -R go+rX $MLFLOW_ARTIFACT_ROOT" did not complete successfully: exit code: 1`





```

**Comment by jomariya23156** [comment] 2024-04-27 04:43
The problem is you're using the incorrect `platform` option in services when building/running images. I'm using a Macbook with an M1 Apple chip and it's `arm64`. So, I explicitly specified `platform: linux/arm64` under every service in docker-compose. If you're using Windows or Linux (mostly), you have to change that to `platform: linux/amd64` or just remove this line and let docker automatically detect the underlying architecture of your system.

**Comment by alexio545** [comment] 2024-04-28 07:08
Thank you for the help but i did everything you have said and its seems to have worked but i think im still facing compatibility issues im using github codespaces and now im now getting the following error after runnning 


`docker-compose -f docker-compose.yml -f docker-compose-airflow.yml up -d`


 ````
 => ERROR [ray 2/4] RUN mkdir -p /storage/mlruns/ &&     chown -R ray /storage/mlruns/ &&     chmod -R go+rX /storage/ml  1.6s
------
 > [ray 2/4] RUN mkdir -p /storage/mlruns/ &&     chown -R ray /storage/mlruns/ &&     chmod -R go+rX /storage/mlruns/:
1.569 exec /bin/bash: exec format error
------
failed to solve: process "/bin/bash -c mkdir -p $MLFLOW_ARTIFACT_ROOT &&     chown -R ray $MLFLOW_ARTIFACT_ROOT &&     chmod -R go+rX $MLFLOW_ARTIFACT_ROOT" did not complete successfully: exit code: 1`
```

**Comment by jomariya23156** [comment] 2024-04-28 07:25
For Ray specifically, you also have to change `ARCH_TRAILING_IMG_NAME` build argument to be empty like this:
```
build:
    context: ./services/ray
    dockerfile: Dockerfile
    args:
        MLFLOW_ARTIFACT_ROOT: ${MLFLOW_ARTIFACT_ROOT}
        # for amd64 (x86_64) please leave ARCH_TRAILING_IMG_NAME empty
        ARCH_TRAILING_IMG_NAME:
```

**Comment by alexio545** [comment] 2024-04-28 21:33
Thank you again it worked , however i now have a challenge in the front   end on streamlit app , im getting this error 

```
`AttributeError: forecast_results
Traceback:
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
File "/service/app/main.py", line 72, in <module>
    forecast_table = get_table_from_engine(engine, FORECAST_TABLE_NAME)
File "/service/app/db_utils.py", line 28, in get_table_from_engine
    table_obj = getattr(Base.classes, table_name)
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 188, in __getattr__
    raise AttributeError(key)`
```

**Comment by jomariya23156** [comment] 2024-04-29 03:16
When you first start the system, there's no model and forecast result for Streamlit to display. You have to trigger the training Airflow DAG (weekly one) once and wait until it's done. Streamlit app should work fine after that. I recommend you to watch and folllow the [demo video ](https://www.youtube.com/watch?v=PwV8TIsMEME)and read [How things work](https://github.com/jomariya23156/sales-forecast-mlops-at-scale?tab=readme-ov-file#how-things-work) section in README.

I'm closing the issue now since the problem is already fixed and it's now just about the setup process you haven't done.

**Closed as completed by jomariya23156** 2024-04-29 03:16 UTC
Labels: platform: github codespace

**Comment by alexio545** [comment] 2024-04-29 04:41
ok thank you , this is a great project and keep on creating content like this it helps us starters to understand how it is to create realworld projects
